set ALFRESCO_ROOT=C:\Alfresco-4.2.c
set MAGICK_HOME=%ALFRESCO_ROOT%\imagemagick
set MAGICK_CODER_MODULE_PATH=%MAGICK_HOME%\modules\coders
set MAGICK_CONFIGURE_PATH=%MAGICK_HOME%\config
set GS_LIB=%MAGICK_HOME%\lib
set DYLD_LIBRARY_PATH=%MAGICK_HOME%\lib
set LD_LIBRARY_PATH=%MAGICK_HOME%\lib

set CONVERT_EXE=%MAGICK_HOME%\convert.exe

%CONVERT_EXE% %1 %2
