set TOMCAT_SERVICE=alfrescoTomcatnum1
set POSTGRE_SERVICE=alfrescoPostgreSQL-1

set ALFRESCO_DIR=C:\Alfresco
set ALFRESCO_DATA_DIR=%ALFRESCO_DIR%\alf_data
set JAVA=%ALFRESCO_DIR%\java\bin\java
set START_ALFRESCO=net start %TOMCAT_SERVICE%
set STOP_ALFRESCO=net stop %TOMCAT_SERVICE%
set EMERGENCY_STOP_ALFRESCO=taskkill /F /FI "Services eq %TOMCAT_SERVICE%"
set START_Postgre=net start %POSTGRE_SERVICE%
set STOP_Postgre=net stop %POSTGRE_SERVICE%
set EMERGENCY_STOP_Postgre=taskkill /F /FI "Services eq %POSTGRE_SERVICE%"
set BACKUP_DIR=C:\Dist\update\backup
set CATALINA_HOME=%ALFRESCO_DIR%\tomcat
set ENABLE_BACKUP=false
set ARTIFACTORY_USER=user
set ARTIFACTORY_PASS=pass
set ARTIFACTORY_SERVER=http://server:port
set ARTIFACT_DIR=artifact
set PATH_TO_ARTIFACTS=%ARTIFACTORY_SERVER%/%ARTIFACT_DIR%

set PROXY_SERVER=http://proxy-server:port
set PROXY_USER=user
set PROXY_PASS=pass
set PROXY_OPTS=--proxy-negotiate

set UPDATE_REPO=true
set UPDATE_SHARE=true

set IDOCS_CORE_VERSION=2.4.0-SNAPSHOT
set IDOCS_CORE_CLASSIFIER=alfresco4.2
set ATTORNEYS_VERSION=0.1-SNAPSHOT
set ATTORNEYS_CLASSIFIER=common
set ORDERS_VERSION=0.1-SNAPSHOT
set ORDERS_CLASSIFIER=common

set IDOCS_CUSTOM_VERSION=1.2.0-SNAPSHOT
set IDOCS_CUSTOM_CLASSIFIER=common
set IDOCS_CUSTOM_NAME=custom

set DB_NAME=alfresco
set DB_USER_NAME=postgres
set DB_USER_PASSWORD=
set DB_HOST=localhost
set DB_PORT=5433

:: multi line strings line separator
set NL=^


:: two empty line above required!

set AMP_1ST_OVERRIDE_REPO=deps/1st-override-repo/%IDOCS_CORE_VERSION%/1st-override-repo-%IDOCS_CORE_VERSION%-%IDOCS_CORE_CLASSIFIER%.amp
set AMP_IDOCS_REPO=deps/idocs-repo/%IDOCS_CORE_VERSION%/idocs-repo-%IDOCS_CORE_VERSION%-%IDOCS_CORE_CLASSIFIER%.amp
set AMP_ATTORNEYS_REPO=deps/attorneys-repo/%ATTORNEYS_VERSION%/attorneys-repo-%ATTORNEYS_VERSION%-%ATTORNEYS_CLASSIFIER%.amp
set AMP_ORDERS_REPO=deps/orders-repo/%ORDERS_VERSION%/orders-repo-%ORDERS_VERSION%-%ORDERS_CLASSIFIER%.amp
set AMP_CUSTOM_REPO=amps/%IDOCS_CUSTOM_NAME%-repo/%IDOCS_CUSTOM_VERSION%/%IDOCS_CUSTOM_NAME%-repo-%IDOCS_CUSTOM_VERSION%-%IDOCS_CUSTOM_CLASSIFIER%.amp
set AMPS=%AMP_1ST_OVERRIDE_REPO%!NL!%AMP_IDOCS_REPO%!NL!%AMP_ATTORNEYS_REPO%!NL!%AMP_ORDERS_REPO%!NL!%AMP_CUSTOM_REPO%

set AMP_1ST_OVERRIDE_SHARE=deps_share/1st-override-share/%IDOCS_CORE_VERSION%/1st-override-share-%IDOCS_CORE_VERSION%-%IDOCS_CORE_CLASSIFIER%.amp
set AMP_IDOCS_SHARE=deps_share/idocs-share/%IDOCS_CORE_VERSION%/idocs-share-%IDOCS_CORE_VERSION%-%IDOCS_CORE_CLASSIFIER%.amp
set AMP_ATTORNEYS_SHARE=deps_share/attorneys-share/%ATTORNEYS_VERSION%/attorneys-share-%ATTORNEYS_VERSION%-%ATTORNEYS_CLASSIFIER%.amp
set AMP_ORDERS_SHARE=deps_share/orders-share/%ORDERS_VERSION%/orders-share-%ORDERS_VERSION%-%ORDERS_CLASSIFIER%.amp
set AMP_CUSTOM_SHARE=amps_share/%IDOCS_CUSTOM_NAME%-share/%IDOCS_CUSTOM_VERSION%/%IDOCS_CUSTOM_NAME%-share-%IDOCS_CUSTOM_VERSION%-%IDOCS_CUSTOM_CLASSIFIER%.amp
set AMPS_SHARE=%AMP_1ST_OVERRIDE_SHARE%!NL!%AMP_IDOCS_SHARE%!NL!%AMP_ATTORNEYS_SHARE%!NL!%AMP_ORDERS_SHARE%!NL!%AMP_CUSTOM_SHARE%

set zip="C:\Program Files\7-Zip\7z.exe"

set WGET="C:\path\to\wget.exe" --user="%ARTIFACTORY_USER%" --password="%ARTIFACTORY_PASS%" 
set CURL="C:\path\to\curl.exe" --proxy "%PROXY_SERVER%" --proxy-user %PROXY_USER%:%PROXY_PASS% %PROXY_OPTS% --user %ARTIFACTORY_USER%:%ARTIFACTORY_PASS%

set DOWNLOAD=%CURL%