//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.30 at 02:19:06 PM GMT+07:00
//


package ru.citeck.ecos.journals.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for groupActionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="groupActionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="selected"/>
 *     &lt;enumeration value="filtered"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "groupActionType")
@XmlEnum
public enum GroupActionType {

    @XmlEnumValue("selected")
    SELECTED("selected"),
    @XmlEnumValue("filtered")
    FILTERED("filtered");
    private final String value;

    GroupActionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GroupActionType fromValue(String v) {
        for (GroupActionType c: GroupActionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
